### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#23]
The latest commit by you seems to cause a build error, please check
https://travis-ci.org/Dainanahan/dbparser/builds/474200685

**Comment by alizat** [comment]
Build error was happening due to a missing file that was used locally to generate the visualizations provided in the vignette. The problem was solved by adding the following parameter setting to all of the code blocks in the RMD file:

`eval=FALSE`

This prevented all code from being run during the generation of the vignette, thus avoiding any build errors that may occur.
