### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#36]
**Describe the bug**
There are two datasets are missing in the parser *salts* and *international-brands*

**Comment by alizat** [comment]
I have a comment (which may be added later as an issue itself). Currently, we have an example DrugBank record of a **biotech** drug that we use from time to time when working on dbparser issues (`drugbank_record.xml`).

I think we may need another example record but for a drug of type, **small-molecule**, since there are fields that exist only in one drug type or the other. Preferably, this small molecule would be one that is at least somehow new (i.e. creation date to be 2010 or later).
