### ISSUE TITLE
Rename datasets more properly

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#37]
**Is your feature request related to a problem? Please describe.**
Putting name standard to the retrieved datasets will make dealing with it much more easier in dependent packages and apps, please refer to DrugBank Browser

**Describe the solution you'd like**
- Name should be *DatasetName_Parent(s)Name(s)*, i.e **Drugs.csv**, **Names_Drugs.csv**, etc
- Ignore references and interactions in names

**Comment by alizat** [comment]
Great. I also think that file names would be better if they were all lower case. That is, "drugs.csv" and "names_drugs.csv" instead of "Drugs.csv" and "Names_Drugs.csv".

In addition, I think it might be better if the "Parent" name precedes the "Dataset" name in the file name. That is, "drugs_names.csv" instead of "names_drugs.csv".

To be discussed.

**Comment by MohammedFCIS** [comment]
> Great. I also think that file names would be better if they were all lower case. That is, "drugs.csv" and "names_drugs.csv" instead of "Drugs.csv" and "Names_Drugs.csv".
> 
> In addition, I think it might be better if the "Parent" name precedes the "Dataset" name in the file name. That is, "drugs_names.csv" instead of "names_drugs.csv".
> 
> To be discussed.

They are two different approaches, I am taking the first approach for the sake of DrugBank Browser
