### ISSUE TITLE
All ATC Code Classifications

### ISSUE THREAD

**Issue by lmcewen** [Dainanahan/dbparser#57]
I am using the following line of code to extract ATC code information:

```{r}
library(dbparser)
get_xml_db_rows("~/full database_v5.1.4.xml")
atc <- parse_drug_atc_codes()
```
However, I have noticed that there are missing ATC codes that are present on the DrugBank website ATC classififcation browser. All I want is a list of each ATC code and level description for all available ATC codes. One example is the ATC code "S03AA30" - it doesn't seem to be in the output of parse_drug_atc_codes. There are several others as well.

Thanks for any help!

Lisa

**Comment by MohammedFCIS** [comment]
Dear Dr. @alizat may you please look at this issue? Thank you

**Comment by alizat** [comment]
I verified from [this link](https://www.drugbank.ca/atc?utf8=%E2%9C%93&query=S03AA30) that the ATC code 'S03AA30' does exist on the DrugBank website. However, I also verified from this same link that 'S03AA30' does not contain any drugs under it. That is to say: DrugBank is aware of this ATC code but currently does contain any drugs that belong to it at the moment. This is why you could not find 'S03AA30' when you searched for it using the code snippet you posted above.

The structure of the XML file (that is parsed via dbparser) consists of the list of drugs available at the DrugBank website. The `parse_drug_atc_codes()` function parses the ATC codes of these available drugs. Since none of the drugs at the DrugBank website belong to the ATC code 'S03AA30', it was not returned by the `parse_drug_atc_codes()` function.

In a future release of DrugBank, if drugs belonging to 'S03AA30' get added, it will automatically appear when running the code snippet above.

Hope this helps, and please let me know if you have any further questions.

**Comment by MohammedFCIS** [comment]
@lmcewen ,I hope you found the answer is useful for you. Please feel free to reopen the issue if you have more concerns. Thank you
